syntax enable
colorscheme jellybeans

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

set nocompatible
set tabstop=2
set number
set title
set scrolloff=3
set ruler
set showmode
set title

filetype on

" Display Vagrantfiles as Ruby files
autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby

set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
  set undodir=~/.vim/undo
endif
